name: Dev Build Advanced

#on: push:
#      branches: 
#          - 'main'

on:
  workflow_dispatch: {}

jobs:
  buildWindows:
    #needs: testRunner
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest # for mono builds
    #runs-on: windows-latest # for il2cpp use target platform as build server
    strategy:
      fail-fast: false
      matrix:
        projectName:
          - myProjectName
        projectPath:
          - myProjectPath
        targetPlatform:
          - StandaloneWindows64

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ matrix.projectName }}

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}-release
          path: build/${{ matrix.targetPlatform }}
          retention-days: 2